/** One of Claude Code's own slash commands. */
export interface BuiltinCommand {
  name: string;
  description: string;
  /** Other names that run the same command. */
  aliases: string[];
  /** Bundled skills and workflows run like commands but are Claude's own skills. */
  kind: "command" | "skill";
}

type Entry = [name: string, description: string, aliases?: string[], kind?: "skill"];

/**
 * Claude Code's built-in commands, from https://code.claude.com/docs/en/commands
 * (checked 2026-10-02). Removed commands are left out; aliases sit with their command.
 */
const ENTRIES: Entry[] = [
  ["add-dir", "Add a working folder Claude can read and edit in this session"],
  ["advisor", "Turn the advisor tool on or off, or pick its model"],
  ["agents", "Create or manage subagents"],
  ["artifacts", "List the artifacts you own or that are shared with you"],
  ["autocompact", "Set how full the context gets before it's compacted"],
  ["background", "Detach this session to keep running as a background agent", ["bg"]],
  ["branch", "Branch the conversation to try a different direction"],
  ["btw", "Ask a side question without adding it to the conversation"],
  ["bug", "Report a bug or share your conversation", ["share"]],
  ["cd", "Move this session to another working folder"],
  ["chrome", "Set up Claude in Chrome"],
  ["clear", "Start over with an empty context", ["reset", "new"]],
  ["color", "Set the prompt bar color for this session"],
  ["compact", "Free up context by summarizing the conversation so far"],
  ["config", "Open settings: theme, model and preferences", ["settings"]],
  ["context", "See how much of the context is used, as a grid"],
  ["copy", "Copy Claude's last reply to the clipboard"],
  ["design-login", "Allow design-system access for /design-sync"],
  ["desktop", "Continue this session in the Claude Code desktop app", ["app"]],
  ["diff", "Review the changes in your working tree"],
  ["effort", "Set the effort level, from low to max, or auto"],
  ["exit", "Quit Claude Code", ["quit"]],
  ["export", "Export the conversation as plain text"],
  ["fast", "Turn fast mode on or off"],
  ["feedback", "Send feedback about Claude Code"],
  ["focus", "Turn the focus view on or off"],
  ["fork", "Copy the conversation into a new background session"],
  ["goal", "Set a goal Claude keeps working toward across turns"],
  ["heapdump", "Write a memory snapshot to diagnose high memory use"],
  ["help", "Show help and the commands you can use"],
  ["hooks", "See your hook settings"],
  ["ide", "Manage IDE integrations and see their status"],
  ["import", "Bring over settings from Codex, Gemini CLI or Cursor"],
  ["init", "Set up the project with a CLAUDE.md guide"],
  ["insights", "Make a report that analyzes your recent sessions"],
  ["install-github-app", "Install the Claude GitHub app for a repository"],
  ["install-slack-app", "Install the Claude Slack app"],
  ["keybindings", "Open your keyboard shortcuts file"],
  ["list-agents", "List subagents, teammates and other Claude Code sessions", ["peers"]],
  ["login", "Sign in to your Anthropic account"],
  ["logout", "Sign out of your Anthropic account"],
  ["mcp", "Manage MCP server connections and sign-ins"],
  ["memory", "Edit CLAUDE.md files and turn auto memory on or off"],
  ["mobile", "Show a QR code for the Claude mobile app", ["ios", "android"]],
  ["model", "Switch the model and keep it as your default"],
  ["output-style", "List output styles or switch to one"],
  ["passes", "Share a free week of Claude Code with friends"],
  ["permissions", "Manage allow, ask and deny rules for tools", ["allowed-tools"]],
  ["plan", "Go straight into plan mode"],
  ["plugin", "Manage Claude Code plugins"],
  ["powerup", "Learn Claude Code features in short interactive lessons"],
  ["privacy-settings", "See and change your privacy settings"],
  ["radio", "Open Claude FM lo-fi radio in your browser"],
  ["rate-limit-options", "See ways to keep working when you hit a usage limit"],
  ["recap", "Get a one-line summary of this session"],
  ["release-notes", "Browse the changelog by version"],
  ["reload-plugins", "Reload active plugins to apply pending changes"],
  ["reload-skills", "Look again for new skills and commands"],
  ["remote-control", "Let claude.ai control this session remotely", ["rc"]],
  ["remote-env", "Choose the default cloud environment for cloud sessions"],
  ["rename", "Rename this session"],
  ["resume", "Resume a conversation by id or name", ["continue"]],
  ["rewind", "Go back to an earlier point in the conversation or code", ["checkpoint", "undo"]],
  ["sandbox", "Turn sandbox mode on or off"],
  ["schedule", "Create, change, list or run routines", ["routines"]],
  ["scroll-speed", "Adjust mouse wheel scroll speed"],
  ["security-review", "Check this branch's changes for security problems"],
  ["setup-bedrock", "Set up Amazon Bedrock sign-in, region and models"],
  ["setup-vertex", "Set up Google Cloud sign-in for Claude"],
  ["skill-doctor", "See what each skill costs in context and how often it's used"],
  ["skills", "List the skills you have, with filtering and sorting"],
  ["status", "Open settings on the Status tab"],
  ["statusline", "Set up Claude Code's status line"],
  ["stickers", "Order Claude Code stickers"],
  ["stop", "Stop the background session you're attached to"],
  ["subtask", "Hand a task to a forked subagent while you keep working"],
  ["tasks", "See and manage background work in this session", ["bashes"]],
  ["team-onboarding", "Write a team onboarding guide from your usage"],
  ["teleport", "Pull a cloud session into this terminal", ["tp"]],
  ["terminal-setup", "Install Shift+Enter for new lines in your terminal"],
  ["theme", "Change the color theme"],
  ["tui", "Choose the terminal display: default or fullscreen"],
  ["ultrareview", "Run a deep, multi-agent code review in a cloud sandbox"],
  ["upgrade", "Open the upgrade page in your browser"],
  ["usage", "See session cost, plan limits and activity", ["cost", "stats"]],
  ["usage-credits", "Set up usage credits or ask your admin for them"],
  ["voice", "Turn voice dictation on or off"],
  ["web-setup", "Connect GitHub for cloud sessions"],
  ["workflows", "Watch, pause, resume or save running workflows"],
  // Bundled skills: typed like commands.
  ["auto-mode-setup", "Draft auto mode settings from your project", [], "skill"],
  ["autofix-pr", "Start a cloud session that watches this branch's PR and fixes it", [], "skill"],
  ["batch", "Make large changes across the codebase in parallel", [], "skill"],
  ["claude-api", "Load Claude API reference for your project", [], "skill"],
  ["claude-in-chrome", "Have Claude do a task in your browser", [], "skill"],
  ["code-review", "Review the current changes for bugs", ["review"], "skill"],
  ["dataviz", "Guidance for charts, graphs and dashboards", [], "skill"],
  ["debug", "Turn on debug logging and troubleshoot this session", [], "skill"],
  ["deep-research", "Research a question on the web and write a cited report", [], "skill"],
  ["design", "Draft UI mockups, flows, landing pages or posters", [], "skill"],
  ["design-sync", "Upload your repo's React design system to Claude Design", [], "skill"],
  ["doctor", "Check your setup, find problems and fix them", ["checkup"], "skill"],
  [
    "fewer-permission-prompts",
    "Allow common read-only tools to cut permission prompts",
    [],
    "skill",
  ],
  ["loop", "Run a prompt again and again while the session is open", ["proactive"], "skill"],
  ["run", "Start and drive your app to see a change working", [], "skill"],
  ["run-skill-generator", "Teach /run and /verify how to build and drive your app", [], "skill"],
  ["simplify", "Review changed code for cleanups and apply them", [], "skill"],
  ["slides", "Make a new presentation", [], "skill"],
  ["update-config", "Describe a settings change and Claude edits settings.json", [], "skill"],
  ["verify", "Check a change does what it should by running your app", [], "skill"],
];

export const BUILTIN_COMMANDS: BuiltinCommand[] = ENTRIES.map(
  ([name, description, aliases = [], kind]): BuiltinCommand => ({
    name,
    description,
    aliases,
    kind: kind ?? "command",
  }),
).sort((a, b) => a.name.localeCompare(b.name));
