import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { L, slugFor, writeSession } from "../../../../test/helpers/fakeHome";
import { useTmpDir } from "../../../../test/helpers/tmp";
import { MtimeCache } from "../../../core/cache";
import { listSessions } from "../reader";
import type { Session } from "../types";

const tmp = useTmpDir();
const CWD = "C:\\work\\shop";

describe("listSessions", () => {
  it("returns [] when Claude has no projects folder yet", async () => {
    expect(await listSessions(tmp())).toEqual([]);
  });

  it("reads the basics of a chat", async () => {
    const home = tmp();
    const s = writeSession(
      home,
      CWD,
      (c) => [
        L.mode(c),
        L.user(c, "Add a dark mode toggle", "2026-09-10T08:00:00.000Z"),
        L.assistant(c, "claude-opus-5-5", "2026-09-10T08:05:00.000Z"),
      ],
      { gitBranch: "feature/dark" },
    );
    const [r] = await listSessions(home);
    expect(r).toMatchObject({
      id: s.id,
      file: s.file,
      cwd: CWD,
      project: "shop",
      title: "Add a dark mode toggle",
      firstPrompt: "Add a dark mode toggle",
      branch: "feature/dark",
      startedAt: Date.parse("2026-09-10T08:00:00.000Z"),
      lastActiveAt: Date.parse("2026-09-10T08:05:00.000Z"),
      prompts: 1,
      model: "claude-opus-5-5",
      entrypoint: "cli",
      estimated: false,
    });
  });

  it("prefers custom title, then agent name, then the latest AI title, then the first prompt", async () => {
    const home = tmp();
    writeSession(home, CWD, (c) => [L.user(c, "first"), L.aiTitle(c, "Old"), L.aiTitle(c, "New")], {
      id: "00000000-0000-4000-8000-000000000001",
    });
    writeSession(
      home,
      CWD,
      (c) => [L.user(c, "first"), L.aiTitle(c, "AI"), L.agentName(c, "Agent")],
      {
        id: "00000000-0000-4000-8000-000000000002",
      },
    );
    writeSession(
      home,
      CWD,
      (c) => [L.user(c, "first"), L.agentName(c, "Agent"), L.customTitle(c, "Mine")],
      { id: "00000000-0000-4000-8000-000000000003" },
    );
    const byId = Object.fromEntries((await listSessions(home)).map((s) => [s.id, s.title]));
    expect(byId["00000000-0000-4000-8000-000000000001"]).toBe("New");
    expect(byId["00000000-0000-4000-8000-000000000002"]).toBe("Agent");
    expect(byId["00000000-0000-4000-8000-000000000003"]).toBe("Mine");
  });

  it("skips meta lines, tool results and command wrappers when finding the first prompt", async () => {
    const home = tmp();
    writeSession(home, CWD, (c) => [
      L.meta(c, "Caveat: the messages below were generated by the user"),
      L.user(c, "<command-name>/clear</command-name>"),
      L.toolResult(c),
      L.userBlocks(c, "  Fix   the\nlogin bug  "),
    ]);
    const [r] = await listSessions(home);
    expect(r!.firstPrompt).toBe("Fix the login bug");
    expect(r!.prompts).toBe(1);
  });

  it("drops transcripts with no real conversation", async () => {
    const home = tmp();
    writeSession(home, CWD, (c) => [L.mode(c), L.meta(c, "x")]);
    expect(await listSessions(home)).toEqual([]);
  });

  it("survives corrupt and half-written lines", async () => {
    const home = tmp();
    writeSession(home, CWD, (c) => ["{not json", L.user(c, "still works"), '{"type":"assis']);
    const [r] = await listSessions(home);
    expect(r!.title).toBe("still works");
  });

  it("treats a detached HEAD as no branch", async () => {
    const home = tmp();
    writeSession(home, CWD, (c) => [L.user(c, "hi")], { gitBranch: "HEAD" });
    expect((await listSessions(home))[0]!.branch).toBeNull();
  });

  it("collects PR links and the chat it was continued in", async () => {
    const home = tmp();
    const next = "11111111-2222-4333-8444-555555555555";
    writeSession(home, CWD, (c) => [
      L.user(c, "ship it"),
      L.prLink(c, "https://github.com/acme/shop/pull/7"),
      L.prLink(c, "https://github.com/acme/shop/pull/7"),
      L.continuedIn(c, next),
    ]);
    const [r] = await listSessions(home);
    expect(r!.prLinks).toEqual(["https://github.com/acme/shop/pull/7"]);
    expect(r!.continuedIn).toBe(next);
  });

  it("ignores files that are not session transcripts", async () => {
    const home = tmp();
    const dir = join(home, "projects", slugFor(CWD));
    mkdirSync(join(dir, "memory"), { recursive: true });
    writeFileSync(join(dir, "notes.jsonl"), "{}\n");
    writeFileSync(join(dir, "memory", "MEMORY.md"), "#");
    writeFileSync(join(home, "projects", "stray.jsonl"), "{}\n");
    expect(await listSessions(home)).toEqual([]);
  });

  it("sorts newest first", async () => {
    const home = tmp();
    writeSession(home, CWD, (c) => [L.user(c, "old", "2026-01-01T00:00:00.000Z")]);
    writeSession(home, "/home/ana/api", (c) => [L.user(c, "new", "2026-05-01T00:00:00.000Z")]);
    expect((await listSessions(home)).map((s) => s.title)).toEqual(["new", "old"]);
  });

  it("marks counts as estimated for transcripts larger than the read window", async () => {
    const home = tmp();
    const filler = "x".repeat(2000);
    writeSession(home, CWD, (c) =>
      Array.from({ length: 400 }, (_, i) => L.user(c, `prompt ${i} ${filler}`)),
    );
    const [r] = await listSessions(home);
    expect(r!.estimated).toBe(true);
    expect(r!.firstPrompt.startsWith("prompt 0")).toBe(true);
  });

  it("keeps chats whose first and last lines are huge (pasted screenshots)", async () => {
    const home = tmp();
    const img = "A".repeat(400_000);
    writeSession(home, CWD, (c) => [
      { type: "permission-mode", permissionMode: "default", sessionId: c.sessionId },
      {
        ...L.userBlocks(c, "Fix the login page"),
        message: {
          role: "user",
          content: [
            { type: "image", source: { type: "base64", media_type: "image/png", data: img } },
            { type: "text", text: "Fix the login page" },
          ],
        },
      },
      L.assistant(c),
      {
        ...L.toolResult(c),
        message: {
          role: "user",
          content: [
            {
              type: "tool_result",
              tool_use_id: "t",
              content: [{ type: "image", source: { data: img } }],
            },
          ],
        },
      },
    ]);
    const [r] = await listSessions(home);
    expect(r).toMatchObject({
      title: "Fix the login page",
      cwd: CWD,
      prompts: 1,
      estimated: false,
    });
  });

  it("caps very long titles", async () => {
    const home = tmp();
    writeSession(home, CWD, (c) => [L.user(c, "hi"), L.customTitle(c, "x".repeat(1000))]);
    const [r] = await listSessions(home);
    expect(r!.title.length).toBeLessThanOrEqual(200);
    expect(r!.title.endsWith("…")).toBe(true);
  });

  it("reuses cached results for unchanged files", async () => {
    const home = tmp();
    writeSession(home, CWD, (c) => [L.user(c, "cache me")]);
    const cache = new MtimeCache<Session | null>();
    const a = await listSessions(home, cache);
    const b = await listSessions(home, cache);
    expect(b[0]).toBe(a[0]);
  });
});
