import type { SetupSnapshot } from "../../src/extension/setupService";
import { MODEL_ALIASES } from "../../src/features/setup/models";

/** A realistic Setup snapshot for UI tests and the visual preview. */
export function sampleSetup(over: Partial<SetupSnapshot> = {}): SetupSnapshot {
  const home = "/Users/ana/.claude";
  const ws = "/Users/ana/code/shop";
  return {
    workspace: ws,
    claudeJsonPath: "/Users/ana/.claude.json",
    modelOptions: MODEL_ALIASES,
    mcpNeedsAuth: [],
    missingCommands: [],
    pausedHooks: [],
    memoryProjects: [
      {
        slug: "-Users-ana-code-shop",
        dir: "/Users/ana/.claude/projects/-Users-ana-code-shop/memory",
        count: 3,
      },
      {
        slug: "-Users-ana-code-api",
        dir: "/Users/ana/.claude/projects/-Users-ana-code-api/memory",
        count: 2,
      },
    ],
    marketplaces: [
      {
        name: "claude-plugins-official",
        source: "github.com/anthropics/claude-plugins-official",
        official: true,
        lastUpdated: Date.UTC(2026, 8, 30),
      },
    ],
    nested: {
      "permissions.defaultMode": null,
      "sandbox.enabled": null,
      "permissions.disableBypassPermissionsMode": null,
    },
    settings: [
      {
        scope: "user",
        path: `${home}/settings.json`,
        exists: true,
        error: null,
        values: {
          model: { value: "opus" },
          theme: { value: "dark" },
          autoMemoryEnabled: { value: true },
          env: { keys: ["ANTHROPIC_LOG"] },
          permissions: { keys: ["allow", "defaultMode"] },
          enabledPlugins: { entries: { "superpowers@claude-plugins-official": true } },
        },
      },
      {
        scope: "project",
        path: `${ws}/.claude/settings.json`,
        exists: true,
        error: null,
        values: { effortLevel: { value: "high" } },
      },
      {
        scope: "local",
        path: `${ws}/.claude/settings.local.json`,
        exists: false,
        error: null,
        values: {},
      },
      {
        scope: "managed",
        path: "/Library/Application Support/ClaudeCode/managed-settings.json",
        exists: false,
        error: null,
        values: {},
      },
    ],
    plugins: [
      {
        id: "superpowers@claude-plugins-official",
        name: "superpowers",
        marketplace: "claude-plugins-official",
        scope: "user",
        projectPath: null,
        installPath: `${home}/plugins/cache/superpowers`,
        version: "6.4.1",
        description: "Skills for planning, TDD and debugging",
        enabled: true,
        enabledIn: ["user"],
        counts: { skills: 14, agents: 1, commands: 3, hooks: 1, mcpServers: 0 },
        problem: null,
      },
      {
        id: "frontend-design@claude-plugins-official",
        name: "frontend-design",
        marketplace: "claude-plugins-official",
        scope: "user",
        projectPath: null,
        installPath: `${home}/plugins/cache/frontend-design`,
        version: "1.0.0",
        description: "Distinctive, production-grade UI",
        enabled: false,
        enabledIn: [],
        counts: { skills: 1, agents: 0, commands: 0, hooks: 0, mcpServers: 0 },
        problem: null,
      },
    ],
    mcp: [
      {
        name: "github",
        scope: "user",
        source: "/Users/ana/.claude.json",
        plugin: null,
        transport: "http",
        command: null,
        args: [],
        url: "https://api.githubcopilot.com/mcp/",
        envKeys: [],
        headerKeys: ["Authorization"],
        approval: null,
        problem: null,
      },
      {
        name: "postgres",
        scope: "project",
        source: `${ws}/.mcp.json`,
        plugin: null,
        transport: "stdio",
        command: "npx",
        args: ["-y", "@modelcontextprotocol/server-postgres"],
        url: null,
        envKeys: ["DATABASE_URL"],
        headerKeys: [],
        approval: "pending",
        problem: null,
      },
    ],
    hooks: [
      {
        id: `user:${home}/settings.json:Stop:0:0`,
        scope: "user",
        source: `${home}/settings.json`,
        plugin: null,
        event: "Stop",
        matcher: null,
        group: 0,
        index: 0,
        type: "command",
        command: "~/bin/notify.sh",
        url: null,
        timeout: null,
      },
      {
        id: `project:${ws}/.claude/settings.json:PreToolUse:0:0`,
        scope: "project",
        source: `${ws}/.claude/settings.json`,
        plugin: null,
        event: "PreToolUse",
        matcher: "Bash",
        group: 0,
        index: 0,
        type: "command",
        command: "npx prettier --check",
        url: null,
        timeout: 30,
      },
    ],
    permissions: {
      rules: [
        { scope: "user", list: "allow", rule: "Bash(npm test)" },
        { scope: "project", list: "deny", rule: "Read(./.env*)" },
      ],
      defaultMode: [{ scope: "user", mode: "plan" }],
      additionalDirectories: [],
    },
    skills: [
      {
        name: "release-notes",
        description: "Write release notes from merged pull requests",
        scope: "project",
        plugin: null,
        dir: `${ws}/.claude/skills/release-notes`,
        file: `${ws}/.claude/skills/release-notes/SKILL.md`,
        model: null,
        allowedTools: ["Bash(git log *)"],
        userInvocable: true,
        modelInvocable: true,
        linked: false,
        problems: [],
        tags: ["docs", "release"],
        argumentHint: "<version>",
        group: null,
        loaded: true,
        command: "/release-notes",
      },
      {
        name: "deploy",
        description: null,
        scope: "user",
        plugin: null,
        dir: `${home}/skills/deploy`,
        file: `${home}/skills/deploy/SKILL.md`,
        model: null,
        allowedTools: [],
        userInvocable: true,
        modelInvocable: true,
        linked: false,
        problems: ["No description — Claude won't know when to use it"],
        tags: [],
        argumentHint: null,
        group: null,
        loaded: true,
        command: "/deploy",
      },
    ],
    agents: [
      {
        name: "reviewer",
        description: "Reviews diffs for bugs and style",
        tools: ["Read", "Grep"],
        model: "sonnet",
        scope: "user",
        plugin: null,
        file: `${home}/agents/reviewer.md`,
        problems: [],
        skills: [],
      },
    ],
    commands: [
      {
        name: "ship",
        description: "Run tests, bump the version and open a PR",
        argumentHint: "[version]",
        scope: "project",
        plugin: null,
        file: `${ws}/.claude/commands/ship.md`,
        problems: [],
      },
    ],
    memory: {
      claudeMd: [
        { scope: "user", path: `${home}/CLAUDE.md`, exists: true, bytes: 1200, imports: [] },
        { scope: "project", path: `${ws}/CLAUDE.md`, exists: false, bytes: 0, imports: [] },
        {
          scope: "project-dir",
          path: `${ws}/.claude/CLAUDE.md`,
          exists: false,
          bytes: 0,
          imports: [],
        },
        { scope: "local", path: `${ws}/CLAUDE.local.md`, exists: false, bytes: 0, imports: [] },
      ],
      auto: {
        enabled: true,
        dir: `${home}/projects/-Users-ana-code-shop/memory`,
        indexPath: `${home}/projects/-Users-ana-code-shop/memory/MEMORY.md`,
        indexLines: 4,
        indexBytes: 320,
        files: [
          {
            name: "user-role.md",
            path: `${home}/projects/-Users-ana-code-shop/memory/user-role.md`,
            bytes: 200,
            title: "user-role",
            description: "Ana is a backend developer",
            links: ["testing"],
            brokenLinks: [],
            orphan: false,
            type: "user",
            linksIn: [],
            indexEntry: "- [User role](user-role.md) — who Ana is",
            frontmatter: true,
            modified: Date.UTC(2026, 8, 29),
          },
          {
            name: "testing.md",
            path: `${home}/projects/-Users-ana-code-shop/memory/testing.md`,
            bytes: 120,
            title: "testing",
            description: "Run the tests before every commit",
            links: ["release-flow"],
            brokenLinks: ["release-flow"],
            orphan: false,
            type: "feedback",
            linksIn: ["user-role"],
            indexEntry: null,
            frontmatter: true,
            modified: Date.UTC(2026, 8, 30),
          },
          {
            name: "scratch.md",
            path: `${home}/projects/-Users-ana-code-shop/memory/scratch.md`,
            bytes: 40,
            title: "scratch",
            description: null,
            links: [],
            brokenLinks: [],
            orphan: true,
            type: null,
            linksIn: [],
            indexEntry: null,
            frontmatter: false,
            modified: Date.UTC(2026, 8, 20),
          },
        ],
      },
    },
    issues: [
      {
        id: "settings-unknown:user:thme",
        severity: "warning",
        area: "settings",
        title: 'Unknown setting "thme" in your user settings',
        detail: 'Claude Code ignores it. Did you mean "theme"?',
        file: `${home}/settings.json`,
        fix: null,
        claudePrompt: "Fix the typo",
      },
      {
        id: "mcp-pending:postgres",
        severity: "info",
        area: "mcp",
        title: 'Project MCP server "postgres" is waiting for approval',
        detail: "Claude won't use it in this project until you approve it.",
        file: `${ws}/.mcp.json`,
        fix: { kind: "approveMcp", name: "postgres" },
        claudePrompt: null,
      },
    ],
    ...over,
  };
}
